<?php
echo "Current Year:".date("Y")."<br>";  // Return Current Year...
echo "Current Month:".date("M")."<br>";  // Return Current Month...
echo "Current Date:".date("d")."<br>";  // Return Current Year...
echo "Current Day:".date("D")."<br>";  // Return Current Year...
echo "Current Hour:".date("H")."<br>";  // Return Current Year...
echo "Current Min:".date("i")."<br>";  // Return Current Year...
echo "Current Second:".date("s")."<br>";  // Return Current Year...
echo "Current am/pm:".date("a")."<br>";  // Return Current Year...
echo date_default_timezone_get();    // Country Found the this time...
echo date_default_timezone_set("Asia/Kolkata")."<Br>";
echo date('H')."<br>";
echo date("Y-M-d  h:i:s a")."<br>";
echo date("Y-m-d  h:i:s a");

?>